"""Embed Vita buttons in the stock pause art while preserving its lettering.

Generation requires build-vita/GmPause.dat extracted from the user's disc.
The checked-in include is sufficient for normal Vita builds.
"""
import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
ICONS = ROOT / "platforms/vita/assets/buttons"
ARCHIVE = ROOT / "build-vita/GmPause.dat"
OUT = ROOT / "src/melee/gm/vita_pause_exit_prompt.inc"
SCALE = 4
FONT = "C:/Windows/Fonts/arialbd.ttf"


def stock(tobj):
    data = ARCHIVE.read_bytes()
    base = 0x20
    desc = struct.unpack_from(">I", data, base + tobj + 0x4C)[0]
    source = struct.unpack_from(">I", data, base + desc)[0]
    width, height = struct.unpack_from(">HH", data, base + desc + 4)
    assert struct.unpack_from(">I", data, base + desc + 8)[0] == 2
    image = Image.new("RGBA", (width, height))
    blocks_x = (width + 7) // 8
    for y in range(height):
        for x in range(width):
            offset = base + source + ((y // 4) * blocks_x + x // 8) * 32
            value = data[offset + (y % 4) * 8 + x % 8]
            gray, alpha = (value & 15) * 17, (value >> 4) * 17
            image.putpixel((x, y), (gray, gray, gray, alpha))
    return image.resize((width * SCALE, height * SCALE),
                        Image.Resampling.NEAREST)


def icon(image, filename, center, width):
    source = Image.open(ICONS / filename).convert("RGBA")
    source = source.crop(source.getchannel("A").getbbox())
    source.thumbnail((width * SCALE, 18 * SCALE), Image.Resampling.LANCZOS)
    image.alpha_composite(source, (center * SCALE - source.width // 2,
                                   11 * SCALE - source.height // 2))


def label(image, text, center, y, size):
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(FONT, size * SCALE)
    box = draw.textbbox((0, 0), text, font=font)
    draw.text((center * SCALE - (box[2] - box[0]) / 2 - box[0],
               y * SCALE - box[1]), text, font=font, fill="black")


def plus(image, center):
    draw = ImageDraw.Draw(image)
    draw.line(((center - 3) * SCALE, 11 * SCALE,
               (center + 3) * SCALE, 11 * SCALE), fill="white",
              width=2 * SCALE)
    draw.line((center * SCALE, 8 * SCALE, center * SCALE, 14 * SCALE),
              fill="white", width=2 * SCALE)


def finish(image, name):
    image = image.resize((image.width // SCALE, 36), Image.Resampling.LANCZOS)
    preview = Image.new("RGBA", image.size, (55, 50, 60, 255))
    preview.alpha_composite(image)
    preview.resize((image.width * 4, 144)).convert("RGB").save(
        ROOT / f"build-vita/pause-vita-{name}-preview.png")
    return image


exit_image = stock(0x1534)
assert exit_image.size == (124 * SCALE, 36 * SCALE)
# The stock border and RESET lettering stay untouched below the button row.
ImageDraw.Draw(exit_image).rectangle((7 * SCALE, 0, 121 * SCALE, 20 * SCALE),
                                     fill=(0, 0, 0, 0))
for name, center, width, text in (
    ("bumper-left.png", 18, 26, "L"),
    ("bumper-right.png", 51, 26, "R"),
    ("start.png", 102, 32, None),
):
    icon(exit_image, name, center, width)
    if text is not None:
        label(exit_image, text, center, 8, 10)
for center in (35, 77):
    plus(exit_image, center)
exit_image = finish(exit_image, "exit")

retry_image = stock(0x15E0)
assert retry_image.size == (80 * SCALE, 36 * SCALE)
# Keep the stock RETRY lettering and frame, replacing only the Z pill.
ImageDraw.Draw(retry_image).rectangle((12 * SCALE, 0, 66 * SCALE, 20 * SCALE),
                                      fill=(0, 0, 0, 0))
icon(retry_image, "select.png", 40, 44)
retry_image = finish(retry_image, "retry")


def encode(image):
    width, height = image.size
    pixels = image.load()
    result = bytearray()
    for tile_y in range(0, height, 4):
        for tile_x in range(0, (width + 7) // 8 * 8, 8):
            for y in range(tile_y, tile_y + 4):
                for x in range(tile_x, tile_x + 8):
                    if x >= width or y >= height:
                        result.append(0)
                        continue
                    red, green, blue, alpha = pixels[x, y]
                    gray = (red * 299 + green * 587 + blue * 114 + 500) // 1000
                    result.append(((alpha * 15 + 127) // 255 << 4) |
                                  ((gray * 15 + 127) // 255))
    assert len(result) == ((width + 7) // 8) * ((height + 3) // 4) * 32
    return result


lines = ["// Generated by platforms/vita/generate_pause_exit_prompt.py; GX_TF_IA4."]
for name, image in (("gmPause_VitaExitPrompt", exit_image),
                    ("gmPause_VitaRetryPrompt", retry_image)):
    lines.append(f"// {name}: {image.width}x{image.height}.")
    lines.append(f"static const u8 {name}[] ATTRIBUTE_ALIGN(32) = {{")
    data = encode(image)
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in data[i:i + 16]) + ",")
    lines.append("};")
OUT.write_text("\n".join(lines) + "\n")
print(f"Wrote {OUT}")
