#ifndef MELEE_VITA_BUILD_LABEL_H
#define MELEE_VITA_BUILD_LABEL_H

#ifndef MELEE_VITA_RELEASE_VERSION
#define MELEE_VITA_RELEASE_VERSION "dev"
#endif

#ifndef MELEE_VITA_BUILD_NUMBER
#define MELEE_VITA_BUILD_NUMBER "local"
#endif

#ifdef TARGET_PS5
#define MELEE_VITA_PLATFORM_NAME "PS5"
#else
#define MELEE_VITA_PLATFORM_NAME "VITA"
#endif

#define MELEE_VITA_BUILD_LABEL                                               \
    MELEE_VITA_PLATFORM_NAME " " MELEE_VITA_RELEASE_VERSION " BUILD "        \
    MELEE_VITA_BUILD_NUMBER

#endif
